### ISSUE TITLE
Requested api "sendMessageToId" Cannot read property 'evaluate' of undefined

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [robertsLando/node-red-contrib-whatsappbot#8]
Requested api "sendMessageToId" Cannot read property 'evaluate' of undefined

![image](https://user-images.githubusercontent.com/1152426/91778131-06e6d880-ebc8-11ea-8fdd-021d70ab80ff.png)
![image](https://user-images.githubusercontent.com/1152426/91778553-3813d880-ebc9-11ea-9df5-dcb9adefd247.png)

**Comment by andersondeoliveiramachado** [comment]
![image](https://user-images.githubusercontent.com/1152426/91781677-3fd77b00-ebd1-11ea-824a-80d208e30001.png)

Replacing sendMessageToId with sendText, it works perfectly.

**Comment by robertsLando** [comment]
`sendText` is working but it doesn't allow you to send messages to non existing chat. It only works for existing ones. Are you using latest version of this package? Have you updated wa automate to latest version? It is working on my instance and I think it's a compatibility issue with the patch.js of this package that I have made on purpose to add that feature. But seems that with latest versions of wa automate the `page` is now named `_page` so that could be the issue why you see that error
